### ISSUE TITLE
ModuleNotFoundError: No module named 'gkeepapi'

### ISSUE THREAD

**Issue by awmottaz** [ybotspawn/Keep-ULauncher#14]
The plugin crashes when ULauncher starts. Running `ulauncher -v`, I see this error:

```
Traceback (most recent call last):
  File "/home/tony/.local/share/ulauncher/extensions/com.github.ybotspawn.keep-ulauncher/main.py", line 4, in <module>
    import gkeepapi
ModuleNotFoundError: No module named 'gkeepapi'
```

I'm not sure how to fix this. I've installed `gkeepapi` with both `pip` and `pip3`.

```
$ pip show gkeepapi
Name: gkeepapi
Version: 0.11.8
Summary: An unofficial Google Keep API client
Home-page: https://github.com/kiwiz/gkeepapi
Author: Kai
Author-email: z@kwi.li
License: MIT
Location: /home/tony/.local/lib/python2.7/site-packages
Requires: enum34, six, future, gpsoauth
```

```
$ pip3 show gkeepapi
Name: gkeepapi
Version: 0.11.8
Summary: An unofficial Google Keep API client
Home-page: https://github.com/kiwiz/gkeepapi
Author: Kai
Author-email: z@kwi.li
License: MIT
Location: /home/linuxbrew/.linuxbrew/lib/python3.7/site-packages
Requires: future, six, gpsoauth
Required-by:
```

I'm not a Python expert, but this suggests to me that `gkeepapi` should be importable.

```
$ python
Python 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gkeepapi
>>> gkeepapi
<module 'gkeepapi' from '/home/tony/.local/lib/python2.7/site-packages/gkeepapi/__init__.pyc'>
```

```
$ python3
Python 3.7.5 (default, Nov  1 2019, 19:15:52) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gkeepapi
>>> gkeepapi
<module 'gkeepapi' from '/home/linuxbrew/.linuxbrew/Cellar/python/3.7.5/lib/python3.7/site-packages/gkeepapi/__init__.py'>
```

Any help for how to fix the `ModuleNotFoundError` is greatly appreciated!

**Comment by ybotspawn** [comment]
You are correct, it should be importable.  Its interesting you can import it.  Out of curiosity, what version of Python is ulauncher using on your system?  I see you have python2 as your default python environment.  I will add some debug statements to output some environment information

**Comment by awmottaz** [comment]
I believe ULauncher is using python 3 based on the location of the `main.py` file. Is there another way for me to verify this?

**Comment by ybotspawn** [comment]
From your favorite terminal:

`which ulauncher`

'head' the resulting file path

**Comment by awmottaz** [comment]
I installed a `.deb`

```
$ which ulauncher
/usr/bin/ulauncher
```

**Comment by ybotspawn** [comment]
Can you paste the contents of:

`head /usr/bin/ulauncher`

I suspect you'll find the response is #!/bin/python which, based on the message above, would refer to python2, not python3.  Can you try switching the python version, uLauncher uses to run, with Python3?  I seem to remember reading somewhere that uLauncher prefers python3.

**Comment by awmottaz** [comment]
Ah sorry, misunderstood. I'll actually post the full contents of that file, since it is in fact using Python3 (throws an exception if not), and seems to be doing some stuff with filepaths. Maybe that's a hint for why it's not finding this module?

```py
#!/usr/bin/python3
# -*- coding: utf-8 -*-


# DO NOT EDIT THIS FILE

import sys
import os

import locale
locale.textdomain('ulauncher')

if sys.version_info.major < 3:
    raise Exception("Ulauncher should be run with Python 3")

# Add project root directory (enable symlink and trunk execution)
PROJECT_ROOT_DIRECTORY = os.path.abspath(
    os.path.dirname(os.path.dirname(os.path.realpath(sys.argv[0]))))

python_path = []
if (os.path.exists(os.path.join(PROJECT_ROOT_DIRECTORY, 'ulauncher')) and PROJECT_ROOT_DIRECTORY not in sys.path):
    python_path.insert(0, PROJECT_ROOT_DIRECTORY)
    sys.path.insert(0, PROJECT_ROOT_DIRECTORY)
if python_path:
    os.putenv('PYTHONPATH', "%s:%s" % (os.getenv('PYTHONPATH', ''), ':'.join(python_path)))  # for subprocesses

from ulauncher.main import main
main()
```

**Comment by ybotspawn** [comment]
Not that I want you to leave it this way, but what happens when you add 
`import gkeepapi`
in that file?  Just put it somewhere toward the top and restart ulauncher, from a terminal.  I'm curious if its something with gkeepapi or ulauncher itself.

**Comment by awmottaz** [comment]
```
$ ulauncher -v
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 9, in <module>
    import gkeepapi
ModuleNotFoundError: No module named 'gkeepapi'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_ulauncher.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/ulauncher", line 9, in <module>
    import gkeepapi
ModuleNotFoundError: No module named 'gkeepapi'
```

Is this some kind of permissions error?

**Comment by awmottaz** [comment]
Oh! I installed python3 via homebrew! Does this mess things up?

```
$ which python3
/home/linuxbrew/.linuxbrew/bin/python3
```

**Comment by ybotspawn** [comment]
Yeah, that could definitely do it.  Does homebrew have a version of pip you can use to install gkeepapi?  Give that a try

**Comment by awmottaz** [comment]
Got it!

ULauncher is a system-wide install, so I needed to use the system-wide pip3 instead of the pip3 installed in homebrew.

```bash
sudo apt install python3-pip
/usr/bin/pip3 install wheel
/usr/bin/pip3 install gkeepapi
```

Now the extension is working! Thanks for the help, @ybotspawn!
